# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ProvincesScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.



from PyQt5 import QtCore, QtGui, QtWidgets
from qgis.gui import *
import os.path
from qgis.utils import iface
from PyQt5.QtWidgets import QDialog, QApplication
from PyQt5.uic import loadUi
from typing import ValuesView
import os # This is is needed in the pyqgis console also
from qgis.PyQt.QtCore import QSettings, QTranslator, QCoreApplication 
from qgis.PyQt.QtGui import QColor, QIcon , QFont, QPixmap 
from qgis.PyQt.QtWidgets import QAction, QFileDialog, QLineEdit
from qgis.core import *
from qgis.gui import (
    QgsMessageBar,
    QgsOptionsWidgetFactory,
    QgsOptionsPageWidget,
    QgsColorButton,

)
from qgis.PyQt.QtWidgets import (
    QAction,
    QFileDialog,
    QLineEdit,
    QSizePolicy,
    QPushButton,
    QDialog,
    QGridLayout,
    QDialogButtonBox,
)

from qgis.core import (
  QgsVectorDataProvider,
  QgsVectorLayer,
)

import os.path
class Provinces(QDialog):

    ######### Les attributs de la classe Provinces: ##########

    filename= "C:/Users/DELL/Documents/Master/Python/ProjectQGIS/DataProject/Goessc/provinces_tta.geojson"
    layer = QgsVectorLayer(filename, "", "ogr")
    nbr= layer.featureCount()
    headers = ["province", "REGION"]
    ######### Les methodes de la classe Provinces: ##########

    ###### Le constructeur: ##############
    def __init__(self):
        super(Provinces, self).__init__()
        loadUi("C:/Users/DELL/AppData/Roaming/QGIS/QGIS3/profiles/default/python/plugins/pyqgis/ProvincesScreen.ui",self)
        self.pushButton_1.clicked.connect(self.LoadData)
        self.pushButton_2.clicked.connect(self.FiltrerData)


    ###################################################
    #####La fonction LoadData:
    def LoadData(self):
            vlayer = iface.activeLayer()
            iface.mapCanvas().setSelectionColor(QColor('yellow'))
            vlayer.selectAll()
            
            self.tableWidget.setColumnCount(2)
            self.tableWidget.setRowCount(self.nbr)
            self.tableWidget.setHorizontalHeaderLabels(self.headers)
            row=0
            for i in range(0,self.nbr):
                Feature= self.layer.getFeature(i)
                self.tableWidget.setItem(row,0,QtWidgets.QTableWidgetItem(Feature['province']))
                self.tableWidget.setItem(row,1,QtWidgets.QTableWidgetItem(str(Feature['REGION'])))
                row= row+1
    ###################################################
    #####La fonction FiltrerData:

    def FiltrerData(self):
        self.tableWidget.clearContents()
        vlayer = iface.activeLayer()
        province= self.chercher.text()
        iface.mapCanvas().setSelectionColor(QColor('red'))
        vlayer.selectByExpression(" \"province\" ='{}' ".format(province))
        selection = vlayer.selectedFeatures()
        for feature in selection:
            self.tableWidget.setItem(0,0,QtWidgets.QTableWidgetItem(feature['province']))
            self.tableWidget.setItem(0,1,QtWidgets.QTableWidgetItem(str(feature['REGION'])))
        self.tableWidget.setRowCount(1)
    
        

    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(692, 506)
        self.tableWidget = QtWidgets.QTableWidget(Dialog)
        self.tableWidget.setGeometry(QtCore.QRect(20, 290, 651, 201))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.titre = QtWidgets.QLabel(Dialog)
        self.titre.setGeometry(QtCore.QRect(260, 10, 241, 51))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.titre.setFont(font)
        self.titre.setObjectName("titre")
        self.image = QtWidgets.QLabel(Dialog)
        self.image.setGeometry(QtCore.QRect(0, 10, 421, 281))
        self.image.setText("")
        self.image.setPixmap(QtGui.QPixmap("provinceTTA.png"))
        self.image.setObjectName("image")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(420, 80, 161, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_1.setFont(font)
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(600, 200, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.chercher = QtWidgets.QLineEdit(Dialog)
        self.chercher.setGeometry(QtCore.QRect(420, 160, 251, 31))
        self.chercher.setObjectName("chercher")
        self.filtrer = QtWidgets.QLabel(Dialog)
        self.filtrer.setGeometry(QtCore.QRect(420, 130, 161, 16))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.filtrer.setFont(font)
        self.filtrer.setObjectName("filtrer")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.titre.setText(_translate("Dialog", "les provinces de la Region "))
        self.pushButton_1.setText(_translate("Dialog", "Afficher toutes les provinces"))
        self.pushButton_2.setText(_translate("Dialog", "Chercher"))
        self.filtrer.setText(_translate("Dialog", "Filtrer une province:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Provinces()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
